float:
  any:
  - base_args: ['@metric']
    constructor: Pinecone
    disabled: false
    docker_tag: ann-benchmarks-pinecone
    module: ann_benchmarks.algorithms.pinecone
    name: pinecone
    run_groups:
      pinecone1:
        args: [
            [""],
            ["us-east-1-aws"],
            ["index2"],
            [4],
            ["p2.x8"],
            [1],
          ]
        query_args: [[10]]



