float:
  any:
  - base_args: ['@metric']
    constructor: TSVectorpq
    disabled: false
    docker_tag: ann-benchmarks-tsvectorpq
    module: ann_benchmarks.algorithms.tsvectorpq
    name: tsvectorpq
    run_groups:
      tsvector1:
        args: [[64], [10], [1.5], [256]]
        query_args: [[125], [50]]
      