float:
  any:
  - base_args: ['@metric']
    constructor: PGVector
    disabled: false
    docker_tag: ann-benchmarks-pgvector
    module: ann_benchmarks.algorithms.pgvector
    name: pgvector
    run_groups:
      pgvector:
#       args: [[100]]
#       query_args: [[ 0 ]]
#       args: [[400, 1000, 2000]]
#       query_args: [[1, 4, 10, 40, 100]]
#       args: [[100, 200, 400, 1000, 2000, 4000]]
#       query_args: [[1, 2, 4, 10, 20, 40, 100]]
        args: [[400]]
        query_args: [[1, 4, 10, 40, 100]]

