float:
  any:
  - base_args: ['@metric']
    constructor: PGEmbeddingHNSW
    disabled: false
    docker_tag: ann-benchmarks-pg_embedding_hnsw
    module: ann_benchmarks.algorithms.pg_embedding_hnsw
    name: pg_embedding_hnsw
    run_groups:
      M-12:
        arg_groups: [{M: 12, efConstruction: 60}]
        query_args: [[10, 100, 250, 400, 600]]
      M-16:
        arg_groups: [{M: 16, efConstruction: 40}]
        query_args: [[10, 100, 250, 400, 600]]
      M-24:
        arg_groups: [{M: 24, efConstruction: 56}]
        query_args: [[10, 100, 250, 400, 600]]
      M-36:
        arg_groups: [{M: 36, efConstruction: 128}]
        query_args: [[10, 100, 250, 400, 600]]
