float:
  any:
  - base_args: ['@metric']
    constructor: TSVector
    disabled: false
    docker_tag: ann-benchmarks-pgvector
    module: ann_benchmarks.algorithms.pgvector
    name: tsvector
    run_groups:
      tsvector1:
        args: [[50], [10], [1.0]]
        query_args: [[100], [1000]]
      tsvector2:
        args: [[50], [10], [1.2]]
        query_args: [[100], [1000]]
      tsvector3:
        args: [[50], [25], [1.0]]
        query_args: [[100], [1000]]
      tsvector4:
        args: [[50], [50], [1.0]]
        query_args: [[100], [1000]]
      tsvector5:
        args: [[50], [65], [1.0]]
        query_args: [[100], [1000]]
