float:
  any:
  - base_args: ['@metric']
    constructor: TSVector
    disabled: false
    docker_tag: ann-benchmarks-tsvector
    module: ann_benchmarks.algorithms.tsvector
    name: tsvector
    run_groups:
      tsvector1:
        args: [
            ["postgres://ann:ann@localhost:5432/ann"],
            [50], # num_neighbors
            [100], # search_list_size
            [1.2], # max_alpha
            [1], # use_bq
            [0], # pq_vector_length
            [0], # num_bits_per_dimension-  0 is for default
          ]
        query_args: [[10, 75], [75, 300, 400]] # query_search_list_size, query rescore
      #tsvector2:
      #  args: [[50], [10], [1.2]]
      #  query_args: [[10, 50, 50]]
      #tsvector3:
      #  args: [[64], [100], [1.0]]
      #  query_args: [[10, 50, 100]]
      #tsvector4:
      #  args: [[50], [10], [1.0]]
      #  query_args: [[10, 50, 100]]
      #tsvector5:
      #  args: [[50], [100], [1.0]]
      #  query_args: [[10, 50, 100]]
