float:
  any:
  - base_args: ['@metric']
    constructor: TSVector
    disabled: false
    docker_tag: ann-benchmarks-tsvector
    module: ann_benchmarks.algorithms.tsvector
    name: tsvector
    run_groups:
      tsvector1:
        args: [[50], [10], [1.0]]
        query_args: [[10, 50, 100]]
      tsvector2:
        args: [[50], [10], [1.2]]
        query_args: [[10, 50, 50]]
      tsvector3:
        args: [[64], [100], [1.0]]
        query_args: [[10, 50, 100]]
      tsvector4:
        args: [[64], [50], [1.2]]
        query_args: [[10, 50, 100]]
      tsvector5:
        args: [[50], [100], [1.0]]
        query_args: [[10, 50, 100]]