float:
  any:
  - base_args: ['@metric']
    constructor: PGVectorHNSW
    disabled: false
    docker_tag: ann-benchmarks-pgvector-hnsw
    module: ann_benchmarks.algorithms.pgvector_hnsw
    name: pgvector_hnsw
    run_groups:
      pgvector_hnsw1:
        args: [
            ["postgres://ann:ann@localhost:5432/ann"],
            [16], # m
            [64], # ef_construction
          ]
        query_args: [[100]] # ef_search
