float:
  any:
  - base_args: ['@metric']
    constructor: PGVectorHNSW
    disabled: false
    docker_tag: ann-benchmarks-pgvector_hnsw
    module: ann_benchmarks.algorithms.pgvector_hnsw
    name: pgvector_hnsw
    run_groups:
#     M-12:
#       arg_groups: [{M: 12, efConstruction: 60}]
#       query_args: [[10, 100, 400, 600]]
#      M-16:
#        arg_groups: [{M: 16, efConstruction: 40}]
#        query_args: [[10, 100, 400, 600]]
#     M-36:
#       arg_groups: [{M: 36, efConstruction: 128}]
#       query_args: [[10, 100, 400, 600]]
     M-24-SB:
       arg_groups: [{M: 24, efConstruction: 56}]
       query_args: [[10, 40, 100, 250, 600]]