float:
  any:
  - base_args: ['@metric']
    constructor: PGVectorHNSWBQ
    disabled: false
    docker_tag: ann-benchmarks-pgvector-hnsw-bq
    module: ann_benchmarks.algorithms.pgvector_hnsw_bq
    name: pgvector_hnsw_bq
    run_groups:
      pgvector_hnsw_bq1:
        args: [
            ["postgres://ann:ann@localhost:5432/ann"],
            [16], # m
            [64], # ef_construction
          ]
        query_args: [[500, 600, 700, 800, 900, 1000]] # ef_search
